version: '3'

services:
  app:
    build: .
    container_name: appserver
    ports:
      - 5000:5000
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:4.4
    container_name: mongoserver
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:6.2
    container_name: redisserver
    ports:
      - 6379:6379

volumes:
  mongo-data:
